# This is a Docker Compose file for a Django application with PostgreSQL database.
services:
  web:
    build:
      context: .
      dockerfile: DockerFile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/DBMS
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init-sql:/docker-entrypoint-initdb.d/
volumes:
  pgdata:
