# Pull base image
FROM python:3.12-slim-bullseye

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /DBMS

# Install dependencies
COPY Pipfile Pipfile.lock /DBMS/
RUN pip install --upgrade pip && pip install pipenv && pipenv install --system

# Copy the whole project
COPY . /DBMS/
