# Generated by Django 5.2 on 2025-04-27 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_lawyer_lawyer_profile_picture_lawyer_lawyer_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_title', models.CharField(max_length=255)),
                ('case_description', models.TextField()),
                ('case_type', models.CharField(max_length=100)),
                ('case_status', models.CharField(default='Active', max_length=50)),
                ('case_created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='accounts.client')),
                ('lawfirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='accounts.lawfirm')),
                ('lawyers', models.ManyToManyField(blank=True, related_name='cases', to='accounts.lawyer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('case_id', 'lawfirm'), name='unique_case_per_lawfirm')],
            },
        ),
    ]
