# Generated by Django 5.2 on 2025-05-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagereadtracker',
            unique_together={('message', 'reader_content_type', 'reader_object_id')},
        ),
    ]
