# Generated by Django 5.2 on 2025-04-22 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawFirm',
            fields=[
                ('lawfirm_id', models.AutoField(primary_key=True, serialize=False)),
                ('lawfirm_name', models.CharField(max_length=255)),
                ('lawfirm_email', models.EmailField(max_length=254, unique=True)),
                ('lawfirm_contact', models.CharField(max_length=20)),
                ('lawfirm_address', models.TextField()),
                ('password', models.CharField(max_length=128)),
                ('lawfirm_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_contact', models.CharField(max_length=20)),
                ('client_address', models.TextField()),
                ('client_created_at', models.DateTimeField(auto_now_add=True)),
                ('lawfirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.lawfirm')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('client_id', 'lawfirm'), name='unique_client_per_lawfirm')],
            },
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('lawyer_id', models.AutoField(primary_key=True, serialize=False)),
                ('lawyer_name', models.CharField(max_length=200)),
                ('lawyer_email', models.EmailField(max_length=254)),
                ('lawyer_contact', models.CharField(max_length=20)),
                ('lawyer_specialization', models.CharField(max_length=255)),
                ('lawyer_hire_date', models.DateField()),
                ('lawyer_created_at', models.DateTimeField(auto_now_add=True)),
                ('lawfirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyers', to='accounts.lawfirm')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lawyer_id', 'lawfirm'), name='unique_lawyer_per_lawfirm')],
            },
        ),
    ]
