# Generated by Django 5.2 on 2025-04-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='lawyer_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='lawyer_profiles/'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='lawyer_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
