# Generated by Django 5.2 on 2025-05-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lawyer_lawyer_profile_picture_lawyer_lawyer_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawyer',
            old_name='lawyer_salary',
            new_name='lawyer_hourly_rate',
        ),
    ]
