# Generated by Django 5.2 on 2025-05-05 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_lawyer_lawyer_profile_picture_lawyer_lawyer_salary'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=255)),
                ('event_description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('event_type', models.CharField(default='Meeting', max_length=50)),
                ('event_loc', models.CharField(max_length=255)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='cases.case')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observed_events', to='accounts.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to='accounts.lawyer')),
            ],
        ),
    ]
